name: Preetier

# This action works with pull requests and pushes
on:
  push:

jobs:
  prettier-js:
    runs-on: ubuntu-latest
    if: ${{ vars.PRETTIFY_JS == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify js code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js,ts}

  prettier-md:
    runs-on: ubuntu-latest
    if: ${{ vars.PRETTIFY_MD == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify md code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.md
